commonEnglishWordsArray = [
    "the", "be", "to", "of", "and", "a", "in", "that", "have", "I", "it", "for", "not", "on", "with", "he", "as", "you", "do",
    "at", "this", "but", "his", "by", "from", "they", "we", "say", "her", "she", "or", "an", "will", "my", "one", "all", "would", 
    "there", "their", "what", "so", "up", "out", "if", "about", "who", "get", "which", "go", "me", "when", "make", "can", "like",
    "time", "no", "just", "him", "know", "take", "people", "into", "year", "your", "good", "some", "could", "them", "see", "other", 
    "than", "then", "now", "look", "only", "come", "its", "over", "think", "also", "back", "after", "use", "two", "how", "our",
    "work", "first", "well", "way", "even", "new", "want", "because", "any", "these", "give", "day", "most", "us", "where", "many",
    "well", "may", "call", "even", "back", "go", "find", "take", "every", "day", "before", "such", "now", "down", "through", "long",
    "very", "men", "game", "car", "got", "right", "day", "another", "point", "thing", "work", "week", "way", "know", "leave", 
    "move", "live", "love", "number", "play", "song", "keep", "group", "family", "government", "party", "tell", "planet", "water",
    "eat", "need", "hand", "country", "school", "work", "word", "thousand", "good", "little", "real", "red", "white", "old", 
    "color", "large", "second", "slow", "fast", "sad", "happy", "small", "big", "loud", "wet", "dry", "soft", "hard", "deep", 
    "shallow", "strong", "weak", "bright", "dark", "ugly", "beautiful", "rich", "poor", "fat", "thin", "hot", "cold", "empty", 
    "full", "clean", "dirty", "sweet", "sour", "bitter", "delicious", "taste", "smell", "see", "hear", "taste", "touch", "hold",
    "quiet", "loud", "near", "far", "right", "wrong", "correct", "sick", "healthy", "safe", "dangerous", "clean", "dirty", "open", 
    "closed", "heavy", "light", "sharp", "blunt", "easy", "difficult", "simple", "complex", "cheap", "expensive", "early", "late", 
    "smooth", "rough", "young", "old", "short", "long", "high", "low", "age", "size", "length", "width", "thickness", "height", 
    "weight", "temperature", "speed", "time", "distance", "place", "order", "position", "direction", "north", "south", "east", 
    "west", "left", "right", "middle", "front", "back", "side", "top", "bottom", "inside", "outside", "below", "under", "over", 
    "above", "before", "after", "between", "among", "near", "far", "straight", "round", "square", "triangular", "at", "in", "on",
    "by", "with", "from", "away", "to", "towards", "into", "through", "over", "under", "above", "below", "beside", "behind",
    "next", "inside", "outside", "here", "there", "near", "far", "common", "rare", "occasional", "usual", "strange", "normal", 
    "odd", "weird", "different", "same", "another", "such", "own", "alone", "together", "both", "all", "some", "other", "few",
    "several", "many", "much", "more", "most", "little", "less", "least", "enough", "sufficient", "whole", "half", "part", "piece",
    "bit", "bit", "lot", "heap", "pile", "stack", "bunch", "group", "set", "series", "sequence", "order", "row", "line", "queue",
    "rank", "range", "variety", "selection", "choice", "option", "alternative", "decision", "pick", "collection", "assortment",
    "assortment", "assortment", "magnitude", "extent", "area", "area", "area", "place", "location", "spot", "day", "week",
    "month", "year", "era", "date", "million", "billion", "trillion", "century", "decade", "period", "moment", "morn", "edge",
    "dawn", "sunrise", "noon", "sunset", "dusk", "eve", "evening", "night", "midnight", "time", "context", 
    "relation", "reason", "cause", "effect", "result", "consequence", "reaction", "response", "impact", "influence", "difference",
    "connection", "link", "association", "correlation", "correspondence", "relevance", "importance", "significance", "attention",
    "regard", "consideration", "note", "care", "concern", "interest", "passion", "subject", "matter", "issue", "affair", "business",
    "problem", "question", "inquiry", "disagreement", "dispute", "conflict", "argument", "debate", "discussion", "conversation",
    "talk", "communication", "language", "speech", "message", "information", "knowledge", "data", "intelligence", "wisdom",
    "truth", "fact", "opinion", "belief", "faith", "trust", "hope", "confidence", "emotion", "feeling", "sensation", "perception",
    "experience", "memory", "thought", "idea", "concept", "theory", "principle", "law", "rule", "regulation", "guidance",
    "direction", "instruction", "command", "order", "request", "wish", "desire", "need", "necessity", "duty", "responsibility",
    "obligation", "requirement", "demand", "claim", "entitlement", "right", "permission", "allowance", "freedom"
]
